POST http://localhost:8000/api/users
Content-Type: application/json


{
    "email": "test@example.com",
    "username": "testuser",
    "password": "mypassword",
    "firstName": "Test",
    "lastName": "User"
}


POST http://localhost:8000/api/posts
Content-Type: application/json

{ 
    "title": "Post title",
    "content": "This is my first test post",
    "authorId": "1"
}
